//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSA02.DO.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EsquemaREC01 : DbContext
    {
        public EsquemaREC01()
            : base("name=EsquemaREC01")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<REC01_ANULACION> REC01_ANULACION { get; set; }
        public DbSet<REC01_BANCO> REC01_BANCO { get; set; }
        public DbSet<REC01_CONCEPTO> REC01_CONCEPTO { get; set; }
        public DbSet<REC01_CORRELATIVO_RECIBO> REC01_CORRELATIVO_RECIBO { get; set; }
        public DbSet<REC01_CORRELATIVO_USUARIO> REC01_CORRELATIVO_USUARIO { get; set; }
        public DbSet<REC01_ESTADO> REC01_ESTADO { get; set; }
        public DbSet<REC01_EVENTO> REC01_EVENTO { get; set; }
        public DbSet<REC01_MEDIO_PAGO> REC01_MEDIO_PAGO { get; set; }
        public DbSet<REC01_PAIS> REC01_PAIS { get; set; }
        public DbSet<REC01_PARTICIPANTE> REC01_PARTICIPANTE { get; set; }
        public DbSet<REC01_RECIBO> REC01_RECIBO { get; set; }
        public DbSet<REC01_REGION> REC01_REGION { get; set; }
        public DbSet<REC01_TIPO_USUARIO> REC01_TIPO_USUARIO { get; set; }
        public DbSet<REC01_USUARIO> REC01_USUARIO { get; set; }
    }
}
