//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSA02.DO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC01_ANULACION
    {
        public decimal ANULACION { get; set; }
        public Nullable<decimal> RECIBO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public string MOTIVO { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_ANULACION { get; set; }
        public Nullable<System.DateTime> FECHA_ANULACION { get; set; }
        public Nullable<decimal> RECIBO_FISICO { get; set; }
        public string SERIE { get; set; }
    
        public virtual REC01_RECIBO REC01_RECIBO { get; set; }
    }
}
