//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSA02.DO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC01_RECIBO
    {
        public REC01_RECIBO()
        {
            this.REC01_ANULACION = new HashSet<REC01_ANULACION>();
        }
    
        public Nullable<decimal> RECIBO { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string NIT { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<decimal> MEDIO_PAGO { get; set; }
        public Nullable<decimal> BANCO { get; set; }
        public string NUMERO_CHEQUE { get; set; }
        public Nullable<decimal> CONCEPTO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string TOTAL_LETRAS { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> EVENTO { get; set; }
        public string PAIS { get; set; }
        public string OBSERVACION_1 { get; set; }
        public string OBSERVACION_2 { get; set; }
        public string OBSERVACION_3 { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<decimal> RECIBO_FISICO { get; set; }
        public string SERIE_RECIBO { get; set; }
    
        public virtual ICollection<REC01_ANULACION> REC01_ANULACION { get; set; }
        public virtual REC01_BANCO REC01_BANCO { get; set; }
        public virtual REC01_CONCEPTO REC01_CONCEPTO { get; set; }
        public virtual REC01_EVENTO REC01_EVENTO { get; set; }
        public virtual REC01_MEDIO_PAGO REC01_MEDIO_PAGO { get; set; }
        public virtual REC01_PAIS REC01_PAIS { get; set; }
    }
}
